[package]
name = "speet-riscv"
version = "0.1.0"
edition = "2024"
description.workspace = true
license-file.workspace = true


[features]
logging = ["dep:log"]

[dependencies]
log = { version = "0.4", optional = true }
wasm-encoder.workspace = true
yecta = {path = "../../helper/yecta"}
rv-asm.workspace = true
wax-core.workspace = true
speet-wasm-helpers = {path = "../../helper/speet-wasm-helpers"}
speet-memory = {path = "../../helper/speet-memory"}
speet-ordering = {path = "../../helper/speet-ordering"}
speet-traps = {path = "../../helper/speet-traps"}
speet-reach = {path = "../../helper/speet-reach"}
speet-link-core = {path = "../../os/speet-link-core"}
speet-interp = {path = "../../helper/speet-interp"}
speet-abi-stubs = { path = "../../os/speet-abi-stubs" }
speet-host-api = { path = "../../os/speet-host-api" }
speet-plugin-api = { path = "../../plugin/speet-plugin-api" }
binary-io = { path = "../../../../binary-io" }

[dev-dependencies]
object = "0.36"
rv-asm.workspace = true
speet-corpus-harness = { path = "../../test/speet-corpus-harness" }
wasm-encoder.workspace = true
wasmparser = { workspace = true }