[[triple]]
name = "x86_64-linux-gnu"
main_return = 78

[[triple]]
name = "aarch64-linux-gnu"
main_return = 78

[[triple]]
name = "riscv32-unknown-linux-gnu"
main_return = 78

[[triple]]
name = "riscv64-unknown-linux-gnu"
main_return = 78
