[package]
name = "speet-linux-wasi"
version = "0.1.0"
edition = "2024"
description.workspace = true
license-file.workspace = true

[dependencies]
os-linux-wasi        = { path = "../../../../os-emulation/crates/emit/os-linux-wasi" }
os-syscall-emit      = { path = "../../../../os-emulation/crates/emit/os-syscall-emit" }
speet-host-api       = { path = "../speet-host-api" }
speet-link-core      = { path = "../speet-link-core" }
speet-module-target  = { path = "../speet-module-target" }
speet-reach          = { path = "../../helper/speet-reach" }
speet-riscv          = { path = "../../native/speet-riscv" }
rv-asm               = { workspace = true }
wasmparser           = { workspace = true, features = ["validate"] }
wasm-encoder         = { workspace = true, features = ["wasmparser"] }
yecta                = { path = "../../helper/yecta" }

[build-dependencies]
speet-host-mem-shim = { path = "../speet-host-mem-shim" }
