//! Generate checked-in Rust redirect-stub sources from an [`AbiSpec`].

use std::fmt::Write as _;

use binary_io::BinArch;
use speet_abi_spec::{AbiArg, AbiFunction, AbiSpec, AbiValueKind};
use speet_host_api::{ImportManifest, WasmValType};

/// Which guest architectures to emit stubs for.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum StubArch {
    X86_64,
    Aarch64,
}

impl StubArch {
    pub fn parse(s: &str) -> Option<Self> {
        match s {
            "x86_64" | "X86_64" => Some(Self::X86_64),
            "aarch64" | "AArch64" => Some(Self::Aarch64),
            _ => None,
        }
    }

    fn bin_arch(self) -> BinArch {
        match self {
            Self::X86_64 => BinArch::X86_64,
            Self::Aarch64 => BinArch::AArch64,
        }
    }

    fn module_suffix(self) -> &'static str {
        match self {
            Self::X86_64 => "x86_64",
            Self::Aarch64 => "aarch64",
        }
    }
}

/// Codegen inputs.
///
/// By default only [`CodegenConfig::symbols`] are emitted (the checked-in /
/// runtime-wired subset). Set [`CodegenConfig::all_symbols`] to emit every
/// function in the ABI spec (full libc/libSystem baseline → gitignored
/// `.generated/` output).
#[derive(Debug, Clone)]
pub struct CodegenConfig {
    /// Checked-in / wired symbol subset. Ignored when [`Self::all_symbols`] is true.
    pub symbols: Vec<String>,
    /// Emit every function in the spec (libc/libSystem baseline bulk output).
    pub all_symbols: bool,
    pub archs: Vec<StubArch>,
    /// Comment recorded in generated file headers (e.g. source XML path).
    pub source_label: String,
}

impl Default for CodegenConfig {
    fn default() -> Self {
        Self {
            symbols: vec!["write".into(), "exit".into()],
            all_symbols: false,
            archs: vec![StubArch::X86_64, StubArch::Aarch64],
            source_label: String::new(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedFile {
    pub path: String,
    pub contents: String,
}

/// Generate all stub files for `spec` under `config`.
pub fn generate(spec: &AbiSpec, config: &CodegenConfig) -> Result<Vec<GeneratedFile>, String> {
    let symbols = resolve_symbols(spec, config);
    let mut files = Vec::new();
    let mut mod_items = String::new();

    for sym in &symbols {
        let Some(func) = spec.lookup(sym) else {
            return Err(format!("symbol {sym:?} not found in ABI spec"));
        };
        let mod_name = symbol_module_name(sym);
        mod_items.push_str(&format!("pub mod {mod_name};\n"));
        files.push(GeneratedFile {
            path: format!("{mod_name}.rs"),
            contents: emit_symbol_module(func, config)?,
        });
    }

    files.push(GeneratedFile {
        path: "registry.rs".into(),
        contents: emit_registry_rs(config, &symbols),
    });

    mod_items.push_str("pub mod registry;\n");

    files.push(GeneratedFile {
        path: "mod.rs".into(),
        contents: emit_mod_rs(&mod_items, config, &symbols),
    });

    Ok(files)
}

fn resolve_symbols(spec: &AbiSpec, config: &CodegenConfig) -> Vec<String> {
    if config.all_symbols {
        return spec.symbol_names().into_iter().map(str::to_string).collect();
    }
    config.symbols.clone()
}

fn emit_mod_rs(mod_items: &str, config: &CodegenConfig, symbols: &[String]) -> String {
    format!(
        r#"//! @generated by speet-abi-codegen — DO NOT EDIT
//! Source: {source}
//! Symbols: {symbols}
//! Architectures: {archs}
//! Mode: {mode}

{mod_items}
"#,
        source = config.source_label,
        symbols = symbols.join(", "),
        archs = config
            .archs
            .iter()
            .map(|a| a.module_suffix())
            .collect::<Vec<_>>()
            .join(", "),
        mode = if config.all_symbols {
            "all symbols (libc/libSystem baseline)"
        } else {
            "checked-in / wired subset"
        },
        mod_items = mod_items,
    )
}

fn emit_registry_rs(config: &CodegenConfig, symbols: &[String]) -> String {
    let mut out = String::new();
    writeln!(
        out,
        "//! @generated by speet-abi-codegen — DO NOT EDIT\n//! Source: {}\n//! Symbols: {}\n",
        config.source_label,
        symbols.join(", "),
    )
    .unwrap();
    out.push_str("use binary_io::BinArch;\n");
    out.push_str("use speet_plugin_api::external_target::CallingConvention;\n\n");

    write!(out, "pub const STUB_SYMBOLS: &[&str] = &[")
        .unwrap();
    for (i, sym) in symbols.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        write!(out, "{sym:?}").unwrap();
    }
    out.push_str("];\n\n");

    out.push_str("/// Whether a checked-in redirect stub exists for `symbol` (after `_` stripping).\n");
    out.push_str("pub fn has_stub(symbol: &str) -> bool {\n");
    out.push_str("    let bare = symbol.strip_prefix('_').unwrap_or(symbol);\n");
    out.push_str("    STUB_SYMBOLS.contains(&bare)\n");
    out.push_str("}\n\n");

    out.push_str("pub fn calling_convention(arch: BinArch, symbol: &str) -> Option<CallingConvention> {\n");
    out.push_str("    let bare = symbol.strip_prefix('_').unwrap_or(symbol);\n");
    out.push_str("    match bare {\n");
    for sym in symbols {
        let mod_name = symbol_module_name(sym);
        writeln!(out, "        {sym:?} => super::{mod_name}::calling_convention(arch),").unwrap();
    }
    out.push_str("        _ => None,\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str("pub fn pointer_arg_indices(symbol: &str) -> Option<&'static [usize]> {\n");
    out.push_str("    let bare = symbol.strip_prefix('_').unwrap_or(symbol);\n");
    out.push_str("    match bare {\n");
    for sym in symbols {
        let mod_name = symbol_module_name(sym);
        writeln!(
            out,
            "        {sym:?} => Some(super::{mod_name}::POINTER_ARG_INDICES),"
        )
        .unwrap();
    }
    out.push_str("        _ => None,\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str("pub fn fn_ptr_arg_indices(symbol: &str) -> Option<&'static [usize]> {\n");
    out.push_str("    let bare = symbol.strip_prefix('_').unwrap_or(symbol);\n");
    out.push_str("    match bare {\n");
    for sym in symbols {
        let mod_name = symbol_module_name(sym);
        writeln!(
            out,
            "        {sym:?} => Some(super::{mod_name}::FN_PTR_ARG_INDICES),"
        )
        .unwrap();
    }
    out.push_str("        _ => None,\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str("/// Whether `symbol` has fn-ptr parameters rewritten via the guest stub catalog.\n");
    out.push_str("pub fn requires_fn_ptr_rewrite(symbol: &str) -> bool {\n");
    out.push_str("    fn_ptr_arg_indices(symbol).is_some_and(|idx| !idx.is_empty())\n");
    out.push_str("}\n");
    out
}

fn emit_symbol_module(func: &AbiFunction, config: &CodegenConfig) -> Result<String, String> {
    let pointer_indices = data_pointer_arg_indices(func);
    let fn_ptr_indices = fn_ptr_arg_indices(func);
    let mut out = String::new();
    writeln!(
        out,
        "//! @generated by speet-abi-codegen — DO NOT EDIT\n//! symbol: {}\n",
        func.name
    ).unwrap();

    out.push_str("use binary_io::BinArch;\n");
    out.push_str("use speet_plugin_api::external_target::CallingConvention;\n\n");

    writeln!(out, "pub const SYMBOL: &str = {:?};", func.name).unwrap();
    writeln!(out, "pub const HOST_SYMBOL: &str = {:?};", func.name).unwrap();
    write!(
        out,
        "pub const POINTER_ARG_INDICES: &[usize] = &{pointer_indices:?};\n",
    )
    .unwrap();
    write!(
        out,
        "pub const FN_PTR_ARG_INDICES: &[usize] = &{fn_ptr_indices:?};\n\n",
    )
    .unwrap();

    out.push_str("pub fn calling_convention(arch: BinArch) -> Option<CallingConvention> {\n");
    out.push_str("    match arch {\n");
    for stub_arch in &config.archs {
        let cc = calling_convention_for(stub_arch.bin_arch(), func)?;
        write!(out, "        BinArch::{:?} => Some(CallingConvention {{\n", stub_arch.bin_arch()).unwrap();
        write!(out, "            arg_locals: vec!{:?},\n", cc.0).unwrap();
        write!(out, "            arg_wrap_i32: vec!{:?},\n", cc.1).unwrap();
        write!(out, "            result_local: {:?},\n", cc.2).unwrap();
        write!(out, "            result_extend_i32: {},\n", cc.3).unwrap();
        out.push_str("        }),\n");
    }
    out.push_str("        _ => None,\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str("#[cfg(feature = \"native\")]\n");
    out.push_str("pub mod native {\n");
    for stub_arch in &config.archs {
        let suffix = stub_arch.module_suffix();
        writeln!(out, "    pub mod {suffix} {{").unwrap();
        emit_native_module(&mut out, func, *stub_arch, &pointer_indices)?;
        out.push_str("    }\n");
    }
    out.push_str("}\n");

    Ok(out)
}

fn emit_native_module(
    out: &mut String,
    func: &AbiFunction,
    arch: StubArch,
    pointer_indices: &[usize],
) -> Result<(), String> {
    let cc = calling_convention_for(arch.bin_arch(), func)?;
    let arg_regs = cc.0;

    out.push_str("        use speet_abi_stubs::emit::");
    match arch {
        StubArch::X86_64 => out.push_str("x86_64"),
        StubArch::Aarch64 => out.push_str("aarch64"),
    }
    out.push_str(" as emit;\n");

    match arch {
        StubArch::X86_64 => {
            out.push_str("        use portal_solutions_asm_x86_64::X64Arch;\n");
            out.push_str("        use portal_solutions_asm_x86_64::out::WriterCore;\n\n");
        }
        StubArch::Aarch64 => {
            out.push_str("        use portal_solutions_asm_aarch64::AArch64Arch;\n");
            out.push_str("        use portal_solutions_asm_aarch64::out::WriterCore;\n\n");
        }
    }

    writeln!(
        out,
        r#"        pub fn redirect<W, Ctx, E, HostCall>(
            w: &mut W,
            ctx: &mut Ctx,
            mem_base_reg: u8,
            mut host_call: HostCall,
        ) -> Result<(), E>
        where
            W: WriterCore<Ctx, Error = E>,
            HostCall: FnMut(&mut W, &mut Ctx) -> Result<(), E>,
        {{
            let arch = "#,
    )
    .unwrap();
    match arch {
        StubArch::X86_64 => out.push_str("            X64Arch::default();\n"),
        StubArch::Aarch64 => out.push_str("            AArch64Arch::default();\n"),
    }

    for &ptr_idx in pointer_indices {
        let Some(&reg) = arg_regs.get(ptr_idx) else {
            return Err(format!(
                "pointer arg index {ptr_idx} out of range for `{}` on {:?}",
                func.name, arch
            ));
        };
        writeln!(
            out,
            "            emit::add_guest_mem_base(w, ctx, arch, {reg}, mem_base_reg)?;"
        )
        .unwrap();
    }

    out.push_str("            host_call(w, ctx)\n");
    out.push_str("        }\n");
    Ok(())
}

fn symbol_module_name(sym: &str) -> String {
    sym.chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect()
}

fn pointer_arg_indices(func: &AbiFunction) -> Vec<usize> {
    data_pointer_arg_indices(func)
}

fn data_pointer_arg_indices(func: &AbiFunction) -> Vec<usize> {
    func.args
        .iter()
        .enumerate()
        .filter(|(_, a)| is_data_pointer_arg(a))
        .map(|(i, _)| i)
        .collect()
}

fn fn_ptr_arg_indices(func: &AbiFunction) -> Vec<usize> {
    func.args
        .iter()
        .enumerate()
        .filter(|(_, a)| is_fn_ptr_arg(a))
        .map(|(i, _)| i)
        .collect()
}

fn is_fn_ptr_arg(arg: &AbiArg) -> bool {
    arg.function_pointer || arg.kind == AbiValueKind::FunctionPointer
}

fn is_data_pointer_arg(arg: &AbiArg) -> bool {
    (arg.pointer || matches!(arg.kind, AbiValueKind::Pointer | AbiValueKind::Object))
        && !is_fn_ptr_arg(arg)
}

fn is_pointer_arg(arg: &AbiArg) -> bool {
    is_data_pointer_arg(arg) || is_fn_ptr_arg(arg)
}

/// (arg_locals, arg_wrap_i32, result_local, result_extend_i32)
fn calling_convention_for(arch: BinArch, func: &AbiFunction) -> Result<(Vec<u32>, Vec<bool>, Option<u32>, bool), String> {
    let n = func.args.len();
    let arg_locals: Vec<u32> = match arch {
        BinArch::X86_64 => x86_64_arg_locals(n),
        BinArch::AArch64 => (0..n as u32).collect(),
    };
    let arg_wrap_i32 = arg_wrap_i32_from_manifest(func);
    let (result_local, result_extend_i32) = if func.retval.kind == AbiValueKind::Void {
        (None, false)
    } else {
        (Some(0), true)
    };
    Ok((arg_locals, arg_wrap_i32, result_local, result_extend_i32))
}

fn x86_64_arg_locals(n: usize) -> Vec<u32> {
    const ORDER: [u32; 6] = [7, 6, 2, 3, 8, 9]; // RDI, RSI, RDX, RCX, R8, R9
    ORDER.iter().take(n).copied().collect()
}

/// Derive `i32.wrap_i64` flags from the manifest slot that intercepts this symbol.
fn arg_wrap_i32_from_manifest(func: &AbiFunction) -> Vec<bool> {
    let manifest = ImportManifest::native_syscall();
    if let Some((_, import_name)) = manifest.resolve_intercept(&func.name) {
        if let Some(imp) = manifest.func_imports.iter().find(|i| i.name == import_name) {
            return imp
                .params
                .iter()
                .map(|t| matches!(t, WasmValType::I32))
                .collect();
        }
    }
    func.args
        .iter()
        .map(|a| {
            matches!(
                a.bridgesupport_type.as_deref(),
                Some("i" | "I" | "s" | "S" | "c" | "C")
            )
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use speet_abi_spec::parse_bridgesupport;

    const SAMPLE: &str = include_str!("../../../../test-data/abi-spec/libc-minimal.bridgesupport.xml");

    #[test]
    fn generates_write_and_exit_modules() {
        let spec = parse_bridgesupport(SAMPLE).unwrap();
        let files = generate(
            &spec,
            &CodegenConfig {
                source_label: "libc-minimal.bridgesupport.xml".into(),
                ..Default::default()
            },
        )
        .unwrap();
        assert!(files.iter().any(|f| f.path == "write.rs"));
        assert!(files.iter().any(|f| f.path == "exit.rs"));
        let write = files.iter().find(|f| f.path == "write.rs").unwrap();
        assert!(write.contents.contains("POINTER_ARG_INDICES: &[usize] = &[1]"));
        assert!(write.contents.contains("pub mod native"));
        let registry = files.iter().find(|f| f.path == "registry.rs").expect("registry.rs");
        assert!(registry.contents.contains("STUB_SYMBOLS"));
        assert!(registry.contents.contains(r#""write""#));
        assert!(registry.contents.contains("super::write::calling_convention"));
        let mod_rs = files.iter().find(|f| f.path == "mod.rs").unwrap();
        assert!(mod_rs.contents.contains("pub mod registry;"));
    }

    #[test]
    fn generates_printf_with_fn_ptr_indices() {
        let spec = parse_bridgesupport(SAMPLE).unwrap();
        let files = generate(
            &spec,
            &CodegenConfig {
                symbols: vec!["printf".into()],
                source_label: "libc-minimal.bridgesupport.xml".into(),
                ..Default::default()
            },
        )
        .unwrap();
        let printf = files.iter().find(|f| f.path == "printf.rs").unwrap();
        assert!(printf.contents.contains("FN_PTR_ARG_INDICES: &[usize] = &[1]"));
        assert!(printf.contents.contains("POINTER_ARG_INDICES: &[usize] = &[0]"));
        let registry = files.iter().find(|f| f.path == "registry.rs").unwrap();
        assert!(registry.contents.contains("fn_ptr_arg_indices"));
        assert!(registry.contents.contains("requires_fn_ptr_rewrite"));
    }

    #[test]
    fn all_symbols_emits_every_function_in_spec() {
        let spec = parse_bridgesupport(SAMPLE).unwrap();
        let files = generate(
            &spec,
            &CodegenConfig {
                all_symbols: true,
                source_label: "libc-minimal.bridgesupport.xml".into(),
                ..Default::default()
            },
        )
        .unwrap();
        assert!(files.iter().any(|f| f.path == "printf.rs"));
        let registry = files.iter().find(|f| f.path == "registry.rs").unwrap();
        assert!(registry.contents.contains(r#""printf""#));
        let mod_rs = files.iter().find(|f| f.path == "mod.rs").unwrap();
        assert!(mod_rs.contents.contains("all symbols (libc/libSystem baseline)"));
    }
}
