[package]
name = "speet-abi-stubs"
version = "0.1.0"
edition = "2021"
description = "Compatibility shim for `os-abi-stubs`."
publish = false
license-file = "../../../COPYING.md"

[dependencies]
binary-io = { path = "../../../../binary-io" }
os-host-api = { path = "../../../../os-emulation/crates/runtime/os-host-api" }
os-abi-spec = { path = "../../../../os-emulation/crates/abi/os-abi-spec" }
os-abi-stubs = { path = "../../../../os-emulation/crates/abi/os-abi-stubs" }
