[package]
name = "speet-abi-codegen"
version = "0.1.0"
edition = "2021"
description = "Compatibility shim for `os-abi-codegen`."
publish = false
license-file = "../../../COPYING.md"

[dependencies]
os-abi-codegen = { path = "../../../../os-emulation/crates/abi/os-abi-codegen" }
os-abi-spec = { path = "../../../../os-emulation/crates/abi/os-abi-spec" }


